server:
  port: 9006
#注册到Eureka服务中心
eureka:
  client:
    service-url: # 注册到集群，就把多个Eurekaserver地址使用逗号连接起来即可;注册到单实例(非集群模 式)，那就写一个就ok
      defaultZone: http://LagouCloudEurekaServerA:9000/eureka,http://LagouCloudEurekaServerB:9001/eureka
  instance:
    prefer-ip-address: true #服务实例中显示ip，而不是显示主机名(兼容老的eureka版本) # 实例名称: 192.168.1.103:lagou-service-resume:8080，我们可以自定义它
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
spring:
  application:
    name: lagou-cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/shawnanchen/lagou-config-repo.git #配置git服务
          username: ctrol #配置git用户名
          password: 860912. #配置git密码
          search-paths:
            - java
      label: master
  rabbitmq:
    host: 192.168.1.37
    port: 15672
    username: rcx
    password: rcx99
# springboot中暴露健康检查等断点接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  # 暴露健康接口的细节
  endpoint:
    health:
      show-details: always
